version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mount local files to the container
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables polling for file changes
      - WATCHPACK_POLLING=true  # Helps Webpack detect changes
    stdin_open: true  # Keep stdin open
    tty: true  # Allocate a pseudo-TTY
    command: ["npm", "start"]